spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.153.135:8848
  application:
    name: service-comsumer
server:
  port: 18083
management:
  endpoints:
    web:
      exposure:
        include: "*"
